import React from "react";
import logo from "./logo.svg";
import "./App.css";
import HelloWorld from "./components/HelloWorld";
import Card from "./components/Card";
import Content from "./components/Content";
import Nav from "./components/Nav";
import Header from "./components/Header";
import Home from "./components/Home";
import CourseHeader from "./components/CourseHeader";
import CoursePreview from "./components/coursePreview/CoursePreview";
export const DataContext = React.createContext();
function App() {
  let obj = {
    title: "Top courses in Python",
    header: "Expand your career opportunities with Python",
    description:
      "Take one of Udemy’s range of Python courses and learn how to code using this incredibly useful language. Its simple syntax and readability makes Python perfect for Flask, Django, data science, and machine learning. You’ll learn how to build everything from games to sites to apps. Choose from a range of courses that will appeal to both beginners and advanced developers alike.",
    courses: [
      {
        id: 394676,
        title: "Learn Python: The Complete Python Programming Course",
        headline:
          "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
        rating: 4.372561,
        image: "https://img-c.udemycdn.com/course/750x422/394676_ce3d_5.jpg",
        instructors: [
          {
            name: "Avinash Jain",
            jop: "CEO of TheCodex.me - Teaching 500,000+ Students how to code",
            image:
              "https://img-b.udemycdn.com/user/100x100/10260436_946b_6.jpg",
          },
          {
            name: "The Codex",
            jop: "Teaching Python through Projects",
            image: "https://img-b.udemycdn.com/user/100x100/52310762_220a.jpg",
          },
        ],
        price: 16.99,
      },
      {
        id: 396876,
        title: "Learning Python for Data Analysis and Visualization",
        headline:
          "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
        rating: 4.3899083,
        image: "https://img-c.udemycdn.com/course/750x422/396876_cc92_7.jpg",
        instructors: [
          {
            name: "Jose Portilla",
            jop: "Head of Data Science at Pierian Training",
            image: "https://img-c.udemycdn.com/user/100x100/9685726_67e7_4.jpg",
          },
        ],
        price: 19.99,
      },
      {
        id: 405878,
        title: "Python for Beginners - Learn Programming from scratch",
        headline:
          "Python For Beginners : This course is meant for absolute beginners in programming or in python.",
        rating: 4.40372,
        image: "https://img-c.udemycdn.com/course/750x422/405878_e5a0_3.jpg",
        instructors: [
          {
            name: "Edwin Diaz",
            jop: "Web Developer & Premium Instructor - 800,000 students",
            image: "https://img-c.udemycdn.com/user/100x100/6772884_fcfc_2.jpg",
          },
          {
            name: "Coding Faculty Solutions",
            jop: "Coding Faculty",
            image: "https://img-c.udemycdn.com/user/100x100/34613172_6fb4.jpg",
          },
        ],
        price: 14.99,
      },
      {
        id: 426570,
        title: "Learn Python: Python for Beginners",
        headline:
          "Python introduction for beginners. Learn complete Python from scratch!",
        rating: 4.2765956,
        image: "https://img-c.udemycdn.com/course/750x422/426570_1b91_3.jpg",
        instructors: [
          {
            name: "Abrar Hussain",
            jop: "Programmer, Student",
            image:
              "https://img-c.udemycdn.com/user/100x100/10971708_a969_3.jpg",
          },
        ],
        price: 16.99,
      },
      {
        id: 449532,
        title: "Python Beyond the Basics - Object-Oriented Programming",
        headline:
          "From Classes To Inheritance - OOP In-Depth For Python Programmers",
        rating: 4.3240743,
        image: "https://img-c.udemycdn.com/course/750x422/449532_2aa9_7.jpg",
        instructors: [
          {
            name: "Infinite Skills",
            jop: "High Quality Training",
            image: "https://img-c.udemycdn.com/user/100x100/39032_bdc3_5.jpg",
          },
        ],
        price: 17.99,
      },
    ],
  };
  const courseDetails = {
    courses: [
      {
        id: 1,
        topic: "Python",
        image: "https://img-b.udemycdn.com/course/240x135/394676_ce3d_5.jpg",
        title: "Learn Python: The Complete Python Programming Course",
        language: "English",
        subs: "English",
        instructor: {
          name: "Avinash Jain",
          Intro: "CEO of TheCodex.me - Teaching 500,000+ Students how to code",
          Image: "https://img-c.udemycdn.com/user/200_H/10260436_946b_6.jpg",
          Rating: "4.4",
          reviewsNumber: "73,735",
          studentsNumber: "890,586",
          coursesNumber: "16",
          description:
            "Avinash Jain is currently a senior at UC Berkeley majoring in Electrical Engineering and Computer Science. He's the CEO and Founder of TheCodex, an online educational platform focused on bringing the best programming content to hundreds of thousands of students around the world. His programming journey began at the age of 10, starting off with simple Python scripts to crawl the weather. Since then, he's worked at numerous companies and is professionally experienced in Python, iOS Development and Web Development. He's launched a plethora of applications in the App Store amassing thousands of downloads. Additionaly, he's competed and won in several hackathons around the world including PennApps and NWHacks. Avinash has a passion to teach - his enthusiasm and love for programming is evident in every video. For the past 7 years he's been an instructor on Udemy and he loves motivating and enabling others to pursue their programming dreams. He hopes to help students realize the power of programming and jumpstart their careers through his courses. Checkout TheCodex for all of his courses, fantastic discounts, and any guidance or help.",
        },
        rate: "4.4",
        ratingCount: "3,159",
        price: "199.99",
        originalPrice: "679.99",
        Introduction:
          "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
        enrollCount: "19,349",
        lastUpdate: "9/2015",
        overview: [
          "Create their own Python Programs",
          "Parse the Web and Create their own Games",
          "Parse the Web and Create their own Games",
        ],
        sectionsCount: "15",
        lecturesCount: "146",
        totalLength: "14h 42m",
        lectures: [
          "Up and Running With Python",
          "The Basics (Data Types)",
          "Conditions and Loops",
          "Functions!",
          "Classes! (Object Orientated Programming)",
          "File Input/Output",
          "Using Python Modules",
          "Crawling The Web",
          "Beautiful Soup HTML Parsing",
          "MatPlotLib - Charts, Plots and 3D Figures!",
          "Data Analysis with Pandas!",
          "Python GUI with Tkinter",
          "Our First Game (Bounce!)",
          "Our Second Game (Pong!)",
          "What's Next?",
        ],
        lessons: [
          "Installing Python",
          "Hello World",
          "Variables",
          "Multiple Assignment",
          "Data Types and Ints",
          "Strings",
          "Placeholders",
          "Lists/Arrays",
          "List Functions",
          "Dictionaries",
          "Dictionary Functions",
          "Tuples",
          "Exercise Files",
          "If-Else Statements",
          "Relational Operators",
          "Nested If/Else",
          "Elif Statements",
          "Logical Operators",
          "For Loops",
          "While Loops",
          "Nested For Loops",
          "Pass, Break and Continue",
          "Try and Except",
          "Commenting",
          "Quick Tips",
          "Exercise Files",
          "Creating our own Functions",
          "Global and Local Vars",
          "Abs and Bool",
          "Help and Dir",
          "Eval and Exec",
          "Str, Int, Float",
          "Recap and Sum",
          "Basics of Classes",
          "Functions in Classes",
          "Class Attributes",
          "Inheritance",
          "Overriding Methods",
          "Creating a File",
          "Creating a File (Windows)",
          "Reading a File",
          "Writing to a File",
          "Appending to Files",
          "Copying Files",
          "Random Module - Randint",
          "Guessing Game",
          "Guessing Game Challenge",
          "Random Module - Shuffle and Choice",
          "Sys Module",
          "Time Module",
          "Turtle Module",
          "For Loops in Turtle",
          "Up and Down Functions",
          "Coloring in Turtle",
          "Functions in Turtle",
          "Exercise Files",
          "Re Module",
          "Crawling The Web (Stocks)",
          "Stock Quotes (.py)",
          "Crawling The Web (Weather)",
          "Weather (.py)",
          "Crawling The Web (Definition)",
          "Definition (.py)",
          "Intro to Beautiful Soup",
          "Installing the Beautiful Soup Module",
          "Prettify with Soup",
          "Drilling Down",
          "Functions in Soup",
          ".String and .Parent",
          "Searching in Soup",
          "Weather Parsing",
          "Antonym Parsing",
          "Intro to MatPlotLib",
          "First Graph!",
          "Understanding the MatPlotLib Interface",
          "Graph Labels",
          "Creating a Graph from a File",
          "Understanding SubPlots and Figures",
          "Coloring of Graph",
          "Multiple Plots in a Graph",
          "Multiple Graphs in a Figure",
          "What about 3 graphs?",
          "Bar Graphs Intro",
          "Modifying our Bar Graph",
          "Pie Chart Intro",
          "Modifying our Pie Chart",
          "Adding a Legend",
          "3D Graphics Intro",
          "3D Scatter Plots",
          "Multiple 3D Scatter Plots",
          "3D Bar Graphs",
          "3D Wireframes",
          "Intro to Pandas",
          "Series Data Structure",
          "Series Continuation",
          "Data Frames Intro",
          "Creating a CSV",
          "Reading a CSV",
          "Writing to a CSV",
          "Getting our Data",
          "Slicing Data Frames",
          "Data Manipulation",
          "Indexing and More",
          "Merging Data Frames",
          "GroupBy Function",
          "MovieLens Data",
          "Heavy Data Analysis",
          "MatPlotLib with Pandas",
          "Let's Finish This",
          "Tkinter Introduction",
          "Labels",
          "Buttons",
          "Layouts",
          "Fill",
          "Grid Layout",
          "Entries",
          "Check Buttons",
          "GUI Login",
          "Actions on Button Click",
          "Binding Functions",
          "More Binding!",
          "Getting Entry Data",
          "Message Box",
          "Drop Down Menus",
          "Calculator Part 1",
          "Calculator Part 2",
          "Calculator Part 3",
          "Calculator Part 4",
          "Canvas Intro",
          "Canvas Objects",
          "Canvas Fill",
          "Random Rectangle Generator",
          "Text and Arcs",
          "Animations",
          "Creating our Ball",
          "Adding the Game Interface",
          "Adding the Paddle",
          "Final Touches",
          "Recap",
          "Bounce! (.py) (v1/v2/v3)",
          "Creating our Ball",
          "Adding Paddle1",
          "Adding Paddle2",
          "Final Touches",
          "Pong! (.py)",
          "Up and Beyond!",
        ],
        content: [
          [
            ["Up and Running With Python"],
            ["Installing Python", "Hello World"],
          ],
          [
            ["The Basics (Data Types)"],
            [
              "Variables",
              "Multiple Assignment",
              "Data Types and Ints",
              "Strings",
              "Placeholders",
              "Lists/Arrays",
              "List Functions",
              "Dictionaries",
              "Dictionary Functions",
              "Tuples",
              "Exercise Files",
            ],
          ],
          [
            ["Conditions and Loops"],
            [
              "If-Else Statements",
              "Relational Operators",
              "Nested If/Else",
              "Elif Statements",
              "Logical Operators",
              "For Loops",
              "While Loops",
              "Nested For Loops",
              "Pass, Break and Continue",
              "Try and Except",
              "Commenting",
              "Quick Tips",
              "Exercise Files",
            ],
          ],
          [
            ["Functions!"],
            [
              "Creating our own Functions",
              "Global and Local Vars",
              "Abs and Bool",
              "Help and Dir",
              "Eval and Exec",
              "Str, Int, Float",
              "Recap and Sum",
            ],
          ],
          [
            ["Classes! (Object Orientated Programming)"],
            [
              "Basics of Classes",
              "Functions in Classes",
              "Class Attributes",
              "Inheritance",
              "Overriding Methods",
            ],
          ],
          [
            ["File Input/Output"],
            [
              "Creating a File",
              "Creating a File (Windows)",
              "Reading a File",
              "Writing to a File",
              "Appending to Files",
              "Copying Files",
            ],
          ],
          [
            ["Using Python Modules"],
            [
              "Random Module - Randint",
              "Guessing Game",
              "Guessing Game Challenge",
              "Random Module - Shuffle and Choice",
              "Sys Module",
              "Time Module",
              "Turtle Module",
              "For Loops in Turtle",
              "Up and Down Functions",
              "Coloring in Turtle",
              "Functions in Turtle",
              "Exercise Files",
            ],
          ],
          [
            ["Crawling The Web"],
            [
              "Re Module",
              "Crawling The Web (Stocks)",
              "Stock Quotes (.py)",
              "Crawling The Web (Weather)",
              "Weather (.py)",
              "Crawling The Web (Definition)",
              "Definition (.py)",
            ],
          ],
          [
            ["Beautiful Soup HTML Parsing"],
            [
              "Intro to Beautiful Soup",
              "Installing the Beautiful Soup Module",
              "Prettify with Soup",
              "Drilling Down",
              "Functions in Soup",
              ".String and .Parent",
              "Searching in Soup",
              "Weather Parsing",
              "Antonym Parsing",
            ],
          ],
          [
            ["MatPlotLib - Charts, Plots and 3D Figures!"],
            [
              "Intro to MatPlotLib",
              "First Graph!",
              "Understanding the MatPlotLib Interface",
              "Graph Labels",
              "Creating a Graph from a File",
              "Understanding SubPlots and Figures",
              "Coloring of Graph",
              "Multiple Plots in a Graph",
              "Multiple Graphs in a Figure",
              "What about 3 graphs?",
              "Bar Graphs Intro",
              "Modifying our Bar Graph",
              "Pie Chart Intro",
              "Modifying our Pie Chart",
              "Adding a Legend",
              "3D Graphics Intro",
              "3D Scatter Plots",
              "Multiple 3D Scatter Plots",
              "3D Bar Graphs",
              "3D Wireframes",
            ],
          ],
          [
            ["Data Analysis with Pandas!"],
            [
              "Intro to Pandas",
              "Series Data Structure",
              "Series Continuation",
              "Data Frames Intro",
              "Creating a CSV",
              "Reading a CSV",
              "Writing to a CSV",
              "Getting our Data",
              "Slicing Data Frames",
              "Data Manipulation",
              "Indexing and More",
              "Merging Data Frames",
              "GroupBy Function",
              "MovieLens Data",
              "Heavy Data Analysis",
              "MatPlotLib with Pandas",
              "Let's Finish This",
            ],
          ],
          [
            ["Python GUI with Tkinter"],
            [
              "Tkinter Introduction",
              "Labels",
              "Buttons",
              "Layouts",
              "Fill",
              "Grid Layout",
              "Entries",
              "Check Buttons",
              "GUI Login",
              "Actions on Button Click",
              "Binding Functions",
              "More Binding!",
              "Getting Entry Data",
              "Message Box",
              "Drop Down Menus",
              "Calculator Part 1",
              "Calculator Part 2",
              "Calculator Part 3",
              "Calculator Part 4",
              "Canvas Intro",
              "Canvas Objects",
              "Canvas Fill",
              "Random Rectangle Generator",
              "Text and Arcs",
              "Animations",
            ],
          ],
          [
            ["Our First Game (Bounce!)"],
            [
              "Creating our Ball",
              "Adding the Game Interface",
              "Adding the Paddle",
              "Final Touches",
              "Recap",
              "Bounce! (.py) (v1/v2/v3)",
            ],
          ],
          [
            ["Our Second Game (Pong!)"],
            [
              "Creating our Ball",
              "Adding Paddle1",
              "Adding Paddle2",
              "Final Touches",
              "Pong! (.py)",
            ],
          ],
          [["What's Next?"], ["Up and Beyond!"]],
        ],
        requirements: [
          "Macintosh (OSX)/ Windows(Vista and higher) Machine",
          "Internet Connection",
        ],
        description: [
          "Do you want to become a programmer? Do you want to learn how to create games, automate your browser, visualize data, and much more?",
          "If you’re looking to learn Python for the very first time or need a quick brush-up, this is the course for you!",
          "Python has rapidly become one of the most popular programming languages around the world. Compared to other languages such as Java or C++, Python consistently outranks and outperforms these languages in demand from businesses and job availability. The average Python developer makes over $100,000 - this number is only going to grow in the coming years.",
          "The best part? Python is one of the easiest coding languages to learn right now. It doesn’t matter if you have no programming experience or are unfamiliar with the syntax of Python. By the time you finish this course, you'll be an absolute pro at programming!",
          "As an instructor and student on Udemy for almost 4 years, I know what it’s like to be overwhelmed with boring and mundane. I promise you’ll have a blast learning the ins and outs of python. I’ve successfully taught over 200,000+ students from over 200 countries jumpstart their programming journeys through my courses.",
          "So what are you waiting for? Jumpstart your programming journey and dive into the world of Python by enrolling in this course today!",
        ],
        whoFor:
          "Even if you haven't touched coding before, it won't matter. The easy step-to-step lectures will quickly guide you through everything you'll need to know about coding, mainly Python. This course is here for you to get accustomed and familiar with Python and its syntax. And above all, Python is one of the easiest coding languages to learn, and there's a lot you can do with it.",
        studentFeedback: ["43", "37", "15", "3", "2"],
        reviews: [
          {
            id: 1,
            name: "Asif H.",
            rate: "3",
            content:
              "Sometimes confusing but was able to clarify. Good job nonetheless.",
          },
          {
            id: 2,
            name: "M.S.Swaroop",
            rate: "4",
            content:
              "the course is specialized so that we learn ourselves deeply,simple and easy.",
          },
          {
            id: 3,
            name: "Saurish R.",
            rate: "5",
            content:
              "In depth concepts of python have been clearly explained. Good chemistry between student and instructor. Fantastic course. Completed every vid and had lot of fun.",
          },
          {
            id: 4,
            name: "Shiristi",
            rate: "5",
            content:
              "I can't say as i have not taken that many classes yet but so far it is good. edited( so yeah it was a journey for me many things happen but i am glad they did and also grateful to the person who is guiding me and thanks udemy for these courses really appreciate it !!!)",
          },
          {
            id: 5,
            name: "Ejeshi G.",
            rate: "4",
            content:
              "teacher is good and direct, though not prompt at responding to questions and enquiries.",
          },
        ],
        hoursCount: "14",
        articlesCount: "1",
        downloadableResource: "3",
      },
    ],
  };

  return (
    <div className="App">
      {/*<DataContext.Provider value={[obj, courseDetails]}>
        <Home />
        
  </DataContext.Provider>*/}
      <DataContext.Provider value={[obj, courseDetails]}>
        <CoursePreview />
      </DataContext.Provider>
    </div>
  );
}

export default App;
